name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Files After Checkout Latest commit
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: Ashish
      - name: Log Greeting time
        run: echo "${{ steps.greet.outputs.time }}"
