name: Repo DispatchAction

on:
  repository_dispatch:
    types: [build]
  pull_request:
    types: [closed, assigned, opened, reopened]
  push:
    branches:
      - master
      - 'release**'
      - '!premaster'
    tags:
      - v1

jobs:
  run-github-repo-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Payload
        run: echo ${{ github.event.client_payload.env }}