name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Github Workflow"
      - name: multiline script
        run: |
          node -v
          npm -v
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"] #Will Run/Cause Serial Running of Jobs
    steps:
      - name: Dir PowerShell
        run: Get-Location
      - name: Dir Bash
        run: pwd
        shell: bash